# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Box / OS
VAGRANT_BOX = 'hashicorp/bionic64'

# Memorable name for your
VM_NAME = 'oah-bes-vm.dev'

# VM User — 'vagrant' by default
VM_USER = 'vagrant'


Vagrant.configure(2) do |config|
  # Vagrant box from Hashicorp
  config.vm.box = VAGRANT_BOX

  # Actual machine name
  config.vm.hostname = VM_NAME
  # Set VM name in Virtualbox
  config.vm.provider "virtualbox" do |v|
    v.name = VM_NAME
    v.memory = 6144
  end


 $script = <<-'SCRIPT'
 git config --global http.sslverify false
 git clone https://github.com/jobyko/oah-bes-vm.git
 mkdir -p /home/vagrant/oah-bes-vm/provisioning/roles
 sudo sed -i 's/archive/in.archive/g' /etc/apt/sources.list
 sudo apt-get update
 sudo apt-get install -y --no-install-recommends ansible
 git clone https://github.com/jobyko/ansible-role-oah-desktop.git #/home/vagrant/oah-bes-vm/provisioning/roles
 git clone https://github.com/jobyko/ansible-role-oah-bes.git #/home/vagrant/oah-bes-vm/provisioning/roles
 sudo mv ansible-role-oah-desktop oah.desktop
 sudo mv ansible-role-oah-bes oah.bes
 sudo mv oah.bes oah.desktop /home/vagrant/oah-bes-vm/provisioning/roles
 SCRIPT

  config.vm.provision "shell", inline: $script

  config.vm.provider :virtualbox do |vb|
   vb.gui = true
  end

 config.vm.provision "ansible_local" do |ansible|
     ansible.playbook = "/home/vagrant/oah-bes-vm/provisioning/oah-install.yml"
  end
end
